name: Docker Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t img-api-msg .
      - name: Tag Docker Image
        run: docker tag img-api-msg iriscafe50/img-api-msg:latest

      - name: Push Docker Image
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push iriscafe50/img-api-msg:latest
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop $(docker ps -q)
            docker pull iriscafe50/img-api-msg:latest
            docker run -d -p 3000:3000 iriscafe50/img-api-msg:latest
